### ISSUE TITLE
Sluggish sound (compared to youtube video)

### ISSUE THREAD

**Issue by CJLove** [SlithyMatt/x16-chasevault#2]
Great job so far!  

Had previously played the 0.1b version with the r34 emulator. Just built the r35 emulator with sound support and tried the 0.2b version.  I noticed that the background music is sluggish, compared to the YouTube video.  Unclear if this is some sort of issue with the emulator or my system (running Fedora 30, ALSA/PulseAudio).

Also noticed that if you die for the last time and the game is over, the sound is stuck on the last note until you elect to "Continue" or otherwise kill the emulator.

**Comment by SlithyMatt** [comment]
The music as you hear it on YouTube is exactly how it sounds on my computer. Are you able to run the emulator fully at speed? If you aren't getting VSYNCs every 1/60th of a second, that could cause the whole game to be sluggish. I have not tried running on Fedora, but I know that at least on Ubuntu, I need to modify the emulator to make the sound performative (apparently, this is an issue for most Linux distros, and does not affect Windows. Try re-building the emulator with main.c modified to set AUDIO_SAMPLES to 256 instead of 4096. It seems like Linux audio drivers just don't get along with the YM2151 emulation. I have no similar problem with other emulators (Deflemask, VGMPlay, etc.), just the X16.

The note-holding bug has been fixed in the master branch and will be in the next beta release.

I'm marking this as closed, but if you still see these issues with the modified emulator and the next beta release (0.3), please feel free to resubmit.

Thanks!
